# Generated by Django 6.0.3 on 2026-04-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_agent_order_delivery_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('picked', 'Picked'), ('delivering', 'Delivering'), ('delivered', 'Delivered')], default='assigned', max_length=20, null=True),
        ),
    ]
