from rest_framework import serializers
from .models import Restaurant


class RestaurantSerializer(serializers.ModelSerializer):
    """
    WHY ModelSerializer again?
    Same reason as before — it reads the Restaurant model
    and auto-generates all fields. Clean and fast.
    """

    class Meta:
        model = Restaurant
        fields = [
            'id', 'name', 'logo', 'cuisine',
            'address', 'phone', 
            'is_active', 'created_at'
        ]
        read_only_fields = ['id', 'created_at']
        """
        WHY read_only_fields here?
        id is auto-generated by PostgreSQL.
        created_at is auto-generated by Django.
        Neither should ever be sent or edited by the client.
        """