# Generated by Django 6.0.3 on 2026-04-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_category_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
