# Generated by Django 6.0.3 on 2026-04-03 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuitem_is_popular_menuitem_is_recommended'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/cuisines/')),
            ],
            options={
                'verbose_name_plural': 'Cuisines',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cuisine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='menu.cuisine'),
        ),
    ]
