# Generated by Django 6.0.3 on 2026-04-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('restaurant', 'Restaurant')], default='customer', max_length=10),
        ),
    ]
