# Generated by Django 6.0.3 on 2026-04-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('restaurant', 'Restaurant'), ('delivery', 'Delivery Agent')], default='customer', max_length=10),
        ),
    ]
